// Code generated by "stringer -type=Attr"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrReset-0]
	_ = x[AttrBold-1]
	_ = x[AttrFaint-2]
	_ = x[AttrItalic-3]
	_ = x[AttrUnderline-4]
	_ = x[AttrBlinkSlow-5]
	_ = x[AttrBlinkRapid-6]
	_ = x[AttrReverseVideo-7]
	_ = x[AttrConceal-8]
	_ = x[AttrStrikethrough-9]
}

const _Attr_name = "AttrResetAttrBoldAttrFaintAttrItalicAttrUnderlineAttrBlinkSlowAttrBlinkRapidAttrReverseVideoAttrConcealAttrStrikethrough"

var _Attr_index = [...]uint8{0, 9, 17, 26, 36, 49, 62, 76, 92, 103, 120}

func (i Attr) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Attr_index)-1 {
		return "Attr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Attr_name[_Attr_index[idx]:_Attr_index[idx+1]]
}
