// Code generated by "stringer -type=BgBrightColor"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBrightBlack-100]
	_ = x[BgBrightRed-101]
	_ = x[BgBrightGreen-102]
	_ = x[BgBrightYellow-103]
	_ = x[BgBrightBlue-104]
	_ = x[BgBrightMagenta-105]
	_ = x[BgBrightCyan-106]
	_ = x[BgBrightWhite-107]
}

const _BgBrightColor_name = "BgBrightBlackBgBrightRedBgBrightGreenBgBrightYellowBgBrightBlueBgBrightMagentaBgBrightCyanBgBrightWhite"

var _BgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i BgBrightColor) String() string {
	idx := int(i) - 100
	if i < 100 || idx >= len(_BgBrightColor_index)-1 {
		return "BgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BgBrightColor_name[_BgBrightColor_index[idx]:_BgBrightColor_index[idx+1]]
}
