// Code generated by "stringer -type=BgColor"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBlack-40]
	_ = x[BgRed-41]
	_ = x[BgGreen-42]
	_ = x[BgYellow-43]
	_ = x[BgBlue-44]
	_ = x[BgMagenta-45]
	_ = x[BgCyan-46]
	_ = x[BgWhite-47]
}

const _BgColor_name = "BgBlackBgRedBgGreenBgYellowBgBlueBgMagentaBgCyanBgWhite"

var _BgColor_index = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}

func (i BgColor) String() string {
	idx := int(i) - 40
	if i < 40 || idx >= len(_BgColor_index)-1 {
		return "BgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BgColor_name[_BgColor_index[idx]:_BgColor_index[idx+1]]
}
