// Code generated by "stringer -type=FgBrightColor"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBrightBlack-90]
	_ = x[FgBrightRed-91]
	_ = x[FgBrightGreen-92]
	_ = x[FgBrightYellow-93]
	_ = x[FgBrightBlue-94]
	_ = x[FgBrightMagenta-95]
	_ = x[FgBrightCyan-96]
	_ = x[FgBrightWhite-97]
}

const _FgBrightColor_name = "FgBrightBlackFgBrightRedFgBrightGreenFgBrightYellowFgBrightBlueFgBrightMagentaFgBrightCyanFgBrightWhite"

var _FgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i FgBrightColor) String() string {
	idx := int(i) - 90
	if i < 90 || idx >= len(_FgBrightColor_index)-1 {
		return "FgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FgBrightColor_name[_FgBrightColor_index[idx]:_FgBrightColor_index[idx+1]]
}
