// Code generated by "stringer -type=FgColor"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBlack-30]
	_ = x[FgRed-31]
	_ = x[FgGreen-32]
	_ = x[FgYellow-33]
	_ = x[FgBlue-34]
	_ = x[FgMagenta-35]
	_ = x[FgCyan-36]
	_ = x[FgWhite-37]
}

const _FgColor_name = "FgBlackFgRedFgGreenFgYellowFgBlueFgMagentaFgCyanFgWhite"

var _FgColor_index = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}

func (i FgColor) String() string {
	idx := int(i) - 30
	if i < 30 || idx >= len(_FgColor_index)-1 {
		return "FgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FgColor_name[_FgColor_index[idx]:_FgColor_index[idx+1]]
}
