// Code generated by "stringer -type=SequenceType"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeqUnknown-0]
	_ = x[SeqEscape-1]
	_ = x[SeqUtf8-2]
	_ = x[SeqCSI-3]
	_ = x[SeqOSC-4]
}

const _SequenceType_name = "SeqUnknownSeqEscapeSeqUtf8SeqCSISeqOSC"

var _SequenceType_index = [...]uint8{0, 10, 19, 26, 32, 38}

func (i SequenceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SequenceType_index)-1 {
		return "SequenceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SequenceType_name[_SequenceType_index[idx]:_SequenceType_index[idx+1]]
}
