// Code generated by "stringer -type=Key,SequenceType,Attr,FgColor,FgBrightColor,BgColor,BgBrightColor -output=vt_string.go"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyUnknown-0]
	_ = x[KeyTab-1]
	_ = x[KeyShiftTab-2]
	_ = x[KeyUp-3]
	_ = x[KeyDown-4]
	_ = x[KeyRight-5]
	_ = x[KeyLeft-6]
	_ = x[KeyHome-7]
	_ = x[KeyEnd-8]
	_ = x[KeyCtrlUp-9]
	_ = x[KeyCtrlDown-10]
	_ = x[KeyCtrlRight-11]
	_ = x[KeyCtrlLeft-12]
	_ = x[KeyAltUp-13]
	_ = x[KeyAltDown-14]
	_ = x[KeyAltRight-15]
	_ = x[KeyAltLeft-16]
	_ = x[KeyShiftUp-17]
	_ = x[KeyShiftDown-18]
	_ = x[KeyShiftRight-19]
	_ = x[KeyShiftLeft-20]
	_ = x[KeySpace-21]
	_ = x[KeyEnter-22]
	_ = x[KeyBackspace-23]
	_ = x[KeyPause-24]
	_ = x[KeyEsc-25]
	_ = x[KeyInsert-26]
	_ = x[KeyDelete-27]
	_ = x[KeyPageUp-28]
	_ = x[KeyPageDown-29]
	_ = x[KeyCtrlEnter-30]
	_ = x[KeyCtrlBackspace-31]
	_ = x[KeyF1-32]
	_ = x[KeyF2-33]
	_ = x[KeyF3-34]
	_ = x[KeyF4-35]
	_ = x[KeyF5-36]
	_ = x[KeyF6-37]
	_ = x[KeyF7-38]
	_ = x[KeyF8-39]
	_ = x[KeyF9-40]
	_ = x[KeyF10-41]
	_ = x[KeyF11-42]
	_ = x[KeyF12-43]
	_ = x[KeyA-44]
	_ = x[KeyB-45]
	_ = x[KeyC-46]
	_ = x[KeyD-47]
	_ = x[KeyE-48]
	_ = x[KeyF-49]
	_ = x[KeyG-50]
	_ = x[KeyH-51]
	_ = x[KeyI-52]
	_ = x[KeyJ-53]
	_ = x[KeyK-54]
	_ = x[KeyL-55]
	_ = x[KeyM-56]
	_ = x[KeyN-57]
	_ = x[KeyO-58]
	_ = x[KeyP-59]
	_ = x[KeyQ-60]
	_ = x[KeyR-61]
	_ = x[KeyS-62]
	_ = x[KeyT-63]
	_ = x[KeyU-64]
	_ = x[KeyV-65]
	_ = x[KeyW-66]
	_ = x[KeyX-67]
	_ = x[KeyY-68]
	_ = x[KeyZ-69]
	_ = x[KeyCtrlA-70]
	_ = x[KeyCtrlB-71]
	_ = x[KeyCtrlC-72]
	_ = x[KeyCtrlD-73]
	_ = x[KeyCtrlE-74]
	_ = x[KeyCtrlF-75]
	_ = x[KeyCtrlG-76]
	_ = x[KeyCtrlH-77]
	_ = x[KeyCtrlI-78]
	_ = x[KeyCtrlJ-79]
	_ = x[KeyCtrlK-80]
	_ = x[KeyCtrlL-81]
	_ = x[KeyCtrlM-82]
	_ = x[KeyCtrlN-83]
	_ = x[KeyCtrlO-84]
	_ = x[KeyCtrlP-85]
	_ = x[KeyCtrlQ-86]
	_ = x[KeyCtrlR-87]
	_ = x[KeyCtrlS-88]
	_ = x[KeyCtrlT-89]
	_ = x[KeyCtrlU-90]
	_ = x[KeyCtrlV-91]
	_ = x[KeyCtrlW-92]
	_ = x[KeyCtrlX-93]
	_ = x[KeyCtrlY-94]
	_ = x[KeyCtrlZ-95]
	_ = x[KeyShiftA-96]
	_ = x[KeyShiftB-97]
	_ = x[KeyShiftC-98]
	_ = x[KeyShiftD-99]
	_ = x[KeyShiftE-100]
	_ = x[KeyShiftF-101]
	_ = x[KeyShiftG-102]
	_ = x[KeyShiftH-103]
	_ = x[KeyShiftI-104]
	_ = x[KeyShiftJ-105]
	_ = x[KeyShiftK-106]
	_ = x[KeyShiftL-107]
	_ = x[KeyShiftM-108]
	_ = x[KeyShiftN-109]
	_ = x[KeyShiftO-110]
	_ = x[KeyShiftP-111]
	_ = x[KeyShiftQ-112]
	_ = x[KeyShiftR-113]
	_ = x[KeyShiftS-114]
	_ = x[KeyShiftT-115]
	_ = x[KeyShiftU-116]
	_ = x[KeyShiftV-117]
	_ = x[KeyShiftW-118]
	_ = x[KeyShiftX-119]
	_ = x[KeyShiftY-120]
	_ = x[KeyShiftZ-121]
	_ = x[KeyAltA-122]
	_ = x[KeyAltB-123]
	_ = x[KeyAltC-124]
	_ = x[KeyAltD-125]
	_ = x[KeyAltE-126]
	_ = x[KeyAltF-127]
	_ = x[KeyAltG-128]
	_ = x[KeyAltH-129]
	_ = x[KeyAltI-130]
	_ = x[KeyAltJ-131]
	_ = x[KeyAltK-132]
	_ = x[KeyAltL-133]
	_ = x[KeyAltM-134]
	_ = x[KeyAltN-135]
	_ = x[KeyAltO-136]
	_ = x[KeyAltP-137]
	_ = x[KeyAltQ-138]
	_ = x[KeyAltR-139]
	_ = x[KeyAltS-140]
	_ = x[KeyAltT-141]
	_ = x[KeyAltU-142]
	_ = x[KeyAltV-143]
	_ = x[KeyAltW-144]
	_ = x[KeyAltX-145]
	_ = x[KeyAltY-146]
	_ = x[KeyAltZ-147]
	_ = x[KeyAlt0-148]
	_ = x[KeyAlt1-149]
	_ = x[KeyAlt2-150]
	_ = x[KeyAlt3-151]
	_ = x[KeyAlt4-152]
	_ = x[KeyAlt5-153]
	_ = x[KeyAlt6-154]
	_ = x[KeyAlt7-155]
	_ = x[KeyAlt8-156]
	_ = x[KeyAlt9-157]
}

const _Key_name = "KeyUnknownKeyTabKeyShiftTabKeyUpKeyDownKeyRightKeyLeftKeyHomeKeyEndKeyCtrlUpKeyCtrlDownKeyCtrlRightKeyCtrlLeftKeyAltUpKeyAltDownKeyAltRightKeyAltLeftKeyShiftUpKeyShiftDownKeyShiftRightKeyShiftLeftKeySpaceKeyEnterKeyBackspaceKeyPauseKeyEscKeyInsertKeyDeleteKeyPageUpKeyPageDownKeyCtrlEnterKeyCtrlBackspaceKeyF1KeyF2KeyF3KeyF4KeyF5KeyF6KeyF7KeyF8KeyF9KeyF10KeyF11KeyF12KeyAKeyBKeyCKeyDKeyEKeyFKeyGKeyHKeyIKeyJKeyKKeyLKeyMKeyNKeyOKeyPKeyQKeyRKeySKeyTKeyUKeyVKeyWKeyXKeyYKeyZKeyCtrlAKeyCtrlBKeyCtrlCKeyCtrlDKeyCtrlEKeyCtrlFKeyCtrlGKeyCtrlHKeyCtrlIKeyCtrlJKeyCtrlKKeyCtrlLKeyCtrlMKeyCtrlNKeyCtrlOKeyCtrlPKeyCtrlQKeyCtrlRKeyCtrlSKeyCtrlTKeyCtrlUKeyCtrlVKeyCtrlWKeyCtrlXKeyCtrlYKeyCtrlZKeyShiftAKeyShiftBKeyShiftCKeyShiftDKeyShiftEKeyShiftFKeyShiftGKeyShiftHKeyShiftIKeyShiftJKeyShiftKKeyShiftLKeyShiftMKeyShiftNKeyShiftOKeyShiftPKeyShiftQKeyShiftRKeyShiftSKeyShiftTKeyShiftUKeyShiftVKeyShiftWKeyShiftXKeyShiftYKeyShiftZKeyAltAKeyAltBKeyAltCKeyAltDKeyAltEKeyAltFKeyAltGKeyAltHKeyAltIKeyAltJKeyAltKKeyAltLKeyAltMKeyAltNKeyAltOKeyAltPKeyAltQKeyAltRKeyAltSKeyAltTKeyAltUKeyAltVKeyAltWKeyAltXKeyAltYKeyAltZKeyAlt0KeyAlt1KeyAlt2KeyAlt3KeyAlt4KeyAlt5KeyAlt6KeyAlt7KeyAlt8KeyAlt9"

var _Key_index = [...]uint16{0, 10, 16, 27, 32, 39, 47, 54, 61, 67, 76, 87, 99, 110, 118, 128, 139, 149, 159, 171, 184, 196, 204, 212, 224, 232, 238, 247, 256, 265, 276, 288, 304, 309, 314, 319, 324, 329, 334, 339, 344, 349, 355, 361, 367, 371, 375, 379, 383, 387, 391, 395, 399, 403, 407, 411, 415, 419, 423, 427, 431, 435, 439, 443, 447, 451, 455, 459, 463, 467, 471, 479, 487, 495, 503, 511, 519, 527, 535, 543, 551, 559, 567, 575, 583, 591, 599, 607, 615, 623, 631, 639, 647, 655, 663, 671, 679, 688, 697, 706, 715, 724, 733, 742, 751, 760, 769, 778, 787, 796, 805, 814, 823, 832, 841, 850, 859, 868, 877, 886, 895, 904, 913, 920, 927, 934, 941, 948, 955, 962, 969, 976, 983, 990, 997, 1004, 1011, 1018, 1025, 1032, 1039, 1046, 1053, 1060, 1067, 1074, 1081, 1088, 1095, 1102, 1109, 1116, 1123, 1130, 1137, 1144, 1151, 1158, 1165}

func (i Key) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Key_index)-1 {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[idx]:_Key_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeqUnknown-0]
	_ = x[SeqEscape-1]
	_ = x[SeqUTF8-2]
	_ = x[SeqCSI-3]
	_ = x[SeqOSC-4]
	_ = x[SeqDCS-5]
	_ = x[SeqSS3-6]
	_ = x[SeqMeta-7]
	_ = x[SeqPaste-8]
}

const _SequenceType_name = "SeqUnknownSeqEscapeSeqUTF8SeqCSISeqOSCSeqDCSSeqSS3SeqMetaSeqPaste"

var _SequenceType_index = [...]uint8{0, 10, 19, 26, 32, 38, 44, 50, 57, 65}

func (i SequenceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SequenceType_index)-1 {
		return "SequenceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SequenceType_name[_SequenceType_index[idx]:_SequenceType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrReset-0]
	_ = x[AttrBold-1]
	_ = x[AttrFaint-2]
	_ = x[AttrItalic-3]
	_ = x[AttrUnderline-4]
	_ = x[AttrBlinkSlow-5]
	_ = x[AttrBlinkRapid-6]
	_ = x[AttrReverseVideo-7]
	_ = x[AttrConceal-8]
	_ = x[AttrStrikethrough-9]
}

const _Attr_name = "AttrResetAttrBoldAttrFaintAttrItalicAttrUnderlineAttrBlinkSlowAttrBlinkRapidAttrReverseVideoAttrConcealAttrStrikethrough"

var _Attr_index = [...]uint8{0, 9, 17, 26, 36, 49, 62, 76, 92, 103, 120}

func (i Attr) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Attr_index)-1 {
		return "Attr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Attr_name[_Attr_index[idx]:_Attr_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBlack-30]
	_ = x[FgRed-31]
	_ = x[FgGreen-32]
	_ = x[FgYellow-33]
	_ = x[FgBlue-34]
	_ = x[FgMagenta-35]
	_ = x[FgCyan-36]
	_ = x[FgWhite-37]
	_ = x[FgDefault-39]
}

const (
	_FgColor_name_0 = "FgBlackFgRedFgGreenFgYellowFgBlueFgMagentaFgCyanFgWhite"
	_FgColor_name_1 = "FgDefault"
)

var (
	_FgColor_index_0 = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}
)

func (i FgColor) String() string {
	switch {
	case 30 <= i && i <= 37:
		i -= 30
		return _FgColor_name_0[_FgColor_index_0[i]:_FgColor_index_0[i+1]]
	case i == 39:
		return _FgColor_name_1
	default:
		return "FgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBrightBlack-90]
	_ = x[FgBrightRed-91]
	_ = x[FgBrightGreen-92]
	_ = x[FgBrightYellow-93]
	_ = x[FgBrightBlue-94]
	_ = x[FgBrightMagenta-95]
	_ = x[FgBrightCyan-96]
	_ = x[FgBrightWhite-97]
}

const _FgBrightColor_name = "FgBrightBlackFgBrightRedFgBrightGreenFgBrightYellowFgBrightBlueFgBrightMagentaFgBrightCyanFgBrightWhite"

var _FgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i FgBrightColor) String() string {
	idx := int(i) - 90
	if i < 90 || idx >= len(_FgBrightColor_index)-1 {
		return "FgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FgBrightColor_name[_FgBrightColor_index[idx]:_FgBrightColor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBlack-40]
	_ = x[BgRed-41]
	_ = x[BgGreen-42]
	_ = x[BgYellow-43]
	_ = x[BgBlue-44]
	_ = x[BgMagenta-45]
	_ = x[BgCyan-46]
	_ = x[BgWhite-47]
	_ = x[BgDefault-49]
}

const (
	_BgColor_name_0 = "BgBlackBgRedBgGreenBgYellowBgBlueBgMagentaBgCyanBgWhite"
	_BgColor_name_1 = "BgDefault"
)

var (
	_BgColor_index_0 = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}
)

func (i BgColor) String() string {
	switch {
	case 40 <= i && i <= 47:
		i -= 40
		return _BgColor_name_0[_BgColor_index_0[i]:_BgColor_index_0[i+1]]
	case i == 49:
		return _BgColor_name_1
	default:
		return "BgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBrightBlack-100]
	_ = x[BgBrightRed-101]
	_ = x[BgBrightGreen-102]
	_ = x[BgBrightYellow-103]
	_ = x[BgBrightBlue-104]
	_ = x[BgBrightMagenta-105]
	_ = x[BgBrightCyan-106]
	_ = x[BgBrightWhite-107]
}

const _BgBrightColor_name = "BgBrightBlackBgBrightRedBgBrightGreenBgBrightYellowBgBrightBlueBgBrightMagentaBgBrightCyanBgBrightWhite"

var _BgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i BgBrightColor) String() string {
	idx := int(i) - 100
	if i < 100 || idx >= len(_BgBrightColor_index)-1 {
		return "BgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BgBrightColor_name[_BgBrightColor_index[idx]:_BgBrightColor_index[idx+1]]
}
