// Code generated by "stringer -type=Key,SequenceType,Attr,FgColor,FgBrightColor,BgColor,BgBrightColor -output=vt_string.go"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyUnknown-0]
	_ = x[KeyTab-1]
	_ = x[KeyShiftTab-2]
	_ = x[KeyUp-3]
	_ = x[KeyDown-4]
	_ = x[KeyRight-5]
	_ = x[KeyLeft-6]
	_ = x[KeyHome-7]
	_ = x[KeyEnd-8]
	_ = x[KeyCtrlUp-9]
	_ = x[KeyCtrlDown-10]
	_ = x[KeyCtrlRight-11]
	_ = x[KeyCtrlLeft-12]
	_ = x[KeyAltUp-13]
	_ = x[KeyAltDown-14]
	_ = x[KeyAltRight-15]
	_ = x[KeyAltLeft-16]
	_ = x[KeyShiftUp-17]
	_ = x[KeyShiftDown-18]
	_ = x[KeyShiftRight-19]
	_ = x[KeyShiftLeft-20]
	_ = x[KeyEnter-21]
	_ = x[KeyBackspace-22]
	_ = x[KeyPause-23]
	_ = x[KeyEsc-24]
	_ = x[KeyInsert-25]
	_ = x[KeyDelete-26]
	_ = x[KeyPageUp-27]
	_ = x[KeyPageDown-28]
	_ = x[KeyCtrlEnter-29]
	_ = x[KeyCtrlBackspace-30]
	_ = x[KeyF1-31]
	_ = x[KeyF2-32]
	_ = x[KeyF3-33]
	_ = x[KeyF4-34]
	_ = x[KeyF5-35]
	_ = x[KeyF6-36]
	_ = x[KeyF7-37]
	_ = x[KeyF8-38]
	_ = x[KeyF9-39]
	_ = x[KeyF10-40]
	_ = x[KeyF11-41]
	_ = x[KeyF12-42]
	_ = x[KeyA-43]
	_ = x[KeyB-44]
	_ = x[KeyC-45]
	_ = x[KeyD-46]
	_ = x[KeyE-47]
	_ = x[KeyF-48]
	_ = x[KeyG-49]
	_ = x[KeyH-50]
	_ = x[KeyI-51]
	_ = x[KeyJ-52]
	_ = x[KeyK-53]
	_ = x[KeyL-54]
	_ = x[KeyM-55]
	_ = x[KeyN-56]
	_ = x[KeyO-57]
	_ = x[KeyP-58]
	_ = x[KeyQ-59]
	_ = x[KeyR-60]
	_ = x[KeyS-61]
	_ = x[KeyT-62]
	_ = x[KeyU-63]
	_ = x[KeyV-64]
	_ = x[KeyW-65]
	_ = x[KeyX-66]
	_ = x[KeyY-67]
	_ = x[KeyZ-68]
	_ = x[KeyCtrlA-69]
	_ = x[KeyCtrlB-70]
	_ = x[KeyCtrlC-71]
	_ = x[KeyCtrlD-72]
	_ = x[KeyCtrlE-73]
	_ = x[KeyCtrlF-74]
	_ = x[KeyCtrlG-75]
	_ = x[KeyCtrlH-76]
	_ = x[KeyCtrlI-77]
	_ = x[KeyCtrlJ-78]
	_ = x[KeyCtrlK-79]
	_ = x[KeyCtrlL-80]
	_ = x[KeyCtrlM-81]
	_ = x[KeyCtrlN-82]
	_ = x[KeyCtrlO-83]
	_ = x[KeyCtrlP-84]
	_ = x[KeyCtrlQ-85]
	_ = x[KeyCtrlR-86]
	_ = x[KeyCtrlS-87]
	_ = x[KeyCtrlT-88]
	_ = x[KeyCtrlU-89]
	_ = x[KeyCtrlV-90]
	_ = x[KeyCtrlW-91]
	_ = x[KeyCtrlX-92]
	_ = x[KeyCtrlY-93]
	_ = x[KeyCtrlZ-94]
	_ = x[KeyShiftA-95]
	_ = x[KeyShiftB-96]
	_ = x[KeyShiftC-97]
	_ = x[KeyShiftD-98]
	_ = x[KeyShiftE-99]
	_ = x[KeyShiftF-100]
	_ = x[KeyShiftG-101]
	_ = x[KeyShiftH-102]
	_ = x[KeyShiftI-103]
	_ = x[KeyShiftJ-104]
	_ = x[KeyShiftK-105]
	_ = x[KeyShiftL-106]
	_ = x[KeyShiftM-107]
	_ = x[KeyShiftN-108]
	_ = x[KeyShiftO-109]
	_ = x[KeyShiftP-110]
	_ = x[KeyShiftQ-111]
	_ = x[KeyShiftR-112]
	_ = x[KeyShiftS-113]
	_ = x[KeyShiftT-114]
	_ = x[KeyShiftU-115]
	_ = x[KeyShiftV-116]
	_ = x[KeyShiftW-117]
	_ = x[KeyShiftX-118]
	_ = x[KeyShiftY-119]
	_ = x[KeyShiftZ-120]
	_ = x[KeyAltA-121]
	_ = x[KeyAltB-122]
	_ = x[KeyAltC-123]
	_ = x[KeyAltD-124]
	_ = x[KeyAltE-125]
	_ = x[KeyAltF-126]
	_ = x[KeyAltG-127]
	_ = x[KeyAltH-128]
	_ = x[KeyAltI-129]
	_ = x[KeyAltJ-130]
	_ = x[KeyAltK-131]
	_ = x[KeyAltL-132]
	_ = x[KeyAltM-133]
	_ = x[KeyAltN-134]
	_ = x[KeyAltO-135]
	_ = x[KeyAltP-136]
	_ = x[KeyAltQ-137]
	_ = x[KeyAltR-138]
	_ = x[KeyAltS-139]
	_ = x[KeyAltT-140]
	_ = x[KeyAltU-141]
	_ = x[KeyAltV-142]
	_ = x[KeyAltW-143]
	_ = x[KeyAltX-144]
	_ = x[KeyAltY-145]
	_ = x[KeyAltZ-146]
	_ = x[KeyAlt0-147]
	_ = x[KeyAlt1-148]
	_ = x[KeyAlt2-149]
	_ = x[KeyAlt3-150]
	_ = x[KeyAlt4-151]
	_ = x[KeyAlt5-152]
	_ = x[KeyAlt6-153]
	_ = x[KeyAlt7-154]
	_ = x[KeyAlt8-155]
	_ = x[KeyAlt9-156]
}

const _Key_name = "KeyUnknownKeyTabKeyShiftTabKeyUpKeyDownKeyRightKeyLeftKeyHomeKeyEndKeyCtrlUpKeyCtrlDownKeyCtrlRightKeyCtrlLeftKeyAltUpKeyAltDownKeyAltRightKeyAltLeftKeyShiftUpKeyShiftDownKeyShiftRightKeyShiftLeftKeyEnterKeyBackspaceKeyPauseKeyEscKeyInsertKeyDeleteKeyPageUpKeyPageDownKeyCtrlEnterKeyCtrlBackspaceKeyF1KeyF2KeyF3KeyF4KeyF5KeyF6KeyF7KeyF8KeyF9KeyF10KeyF11KeyF12KeyAKeyBKeyCKeyDKeyEKeyFKeyGKeyHKeyIKeyJKeyKKeyLKeyMKeyNKeyOKeyPKeyQKeyRKeySKeyTKeyUKeyVKeyWKeyXKeyYKeyZKeyCtrlAKeyCtrlBKeyCtrlCKeyCtrlDKeyCtrlEKeyCtrlFKeyCtrlGKeyCtrlHKeyCtrlIKeyCtrlJKeyCtrlKKeyCtrlLKeyCtrlMKeyCtrlNKeyCtrlOKeyCtrlPKeyCtrlQKeyCtrlRKeyCtrlSKeyCtrlTKeyCtrlUKeyCtrlVKeyCtrlWKeyCtrlXKeyCtrlYKeyCtrlZKeyShiftAKeyShiftBKeyShiftCKeyShiftDKeyShiftEKeyShiftFKeyShiftGKeyShiftHKeyShiftIKeyShiftJKeyShiftKKeyShiftLKeyShiftMKeyShiftNKeyShiftOKeyShiftPKeyShiftQKeyShiftRKeyShiftSKeyShiftTKeyShiftUKeyShiftVKeyShiftWKeyShiftXKeyShiftYKeyShiftZKeyAltAKeyAltBKeyAltCKeyAltDKeyAltEKeyAltFKeyAltGKeyAltHKeyAltIKeyAltJKeyAltKKeyAltLKeyAltMKeyAltNKeyAltOKeyAltPKeyAltQKeyAltRKeyAltSKeyAltTKeyAltUKeyAltVKeyAltWKeyAltXKeyAltYKeyAltZKeyAlt0KeyAlt1KeyAlt2KeyAlt3KeyAlt4KeyAlt5KeyAlt6KeyAlt7KeyAlt8KeyAlt9"

var _Key_index = [...]uint16{0, 10, 16, 27, 32, 39, 47, 54, 61, 67, 76, 87, 99, 110, 118, 128, 139, 149, 159, 171, 184, 196, 204, 216, 224, 230, 239, 248, 257, 268, 280, 296, 301, 306, 311, 316, 321, 326, 331, 336, 341, 347, 353, 359, 363, 367, 371, 375, 379, 383, 387, 391, 395, 399, 403, 407, 411, 415, 419, 423, 427, 431, 435, 439, 443, 447, 451, 455, 459, 463, 471, 479, 487, 495, 503, 511, 519, 527, 535, 543, 551, 559, 567, 575, 583, 591, 599, 607, 615, 623, 631, 639, 647, 655, 663, 671, 680, 689, 698, 707, 716, 725, 734, 743, 752, 761, 770, 779, 788, 797, 806, 815, 824, 833, 842, 851, 860, 869, 878, 887, 896, 905, 912, 919, 926, 933, 940, 947, 954, 961, 968, 975, 982, 989, 996, 1003, 1010, 1017, 1024, 1031, 1038, 1045, 1052, 1059, 1066, 1073, 1080, 1087, 1094, 1101, 1108, 1115, 1122, 1129, 1136, 1143, 1150, 1157}

func (i Key) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Key_index)-1 {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[idx]:_Key_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeqUnknown-0]
	_ = x[SeqEscape-1]
	_ = x[SeqUTF8-2]
	_ = x[SeqCSI-3]
	_ = x[SeqOSC-4]
	_ = x[SeqDCS-5]
	_ = x[SeqSS3-6]
	_ = x[SeqMeta-7]
	_ = x[SeqPaste-8]
}

const _SequenceType_name = "SeqUnknownSeqEscapeSeqUTF8SeqCSISeqOSCSeqDCSSeqSS3SeqMetaSeqPaste"

var _SequenceType_index = [...]uint8{0, 10, 19, 26, 32, 38, 44, 50, 57, 65}

func (i SequenceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SequenceType_index)-1 {
		return "SequenceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SequenceType_name[_SequenceType_index[idx]:_SequenceType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrReset-0]
	_ = x[AttrBold-1]
	_ = x[AttrFaint-2]
	_ = x[AttrItalic-3]
	_ = x[AttrUnderline-4]
	_ = x[AttrBlinkSlow-5]
	_ = x[AttrBlinkRapid-6]
	_ = x[AttrReverseVideo-7]
	_ = x[AttrConceal-8]
	_ = x[AttrStrikethrough-9]
}

const _Attr_name = "AttrResetAttrBoldAttrFaintAttrItalicAttrUnderlineAttrBlinkSlowAttrBlinkRapidAttrReverseVideoAttrConcealAttrStrikethrough"

var _Attr_index = [...]uint8{0, 9, 17, 26, 36, 49, 62, 76, 92, 103, 120}

func (i Attr) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Attr_index)-1 {
		return "Attr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Attr_name[_Attr_index[idx]:_Attr_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBlack-30]
	_ = x[FgRed-31]
	_ = x[FgGreen-32]
	_ = x[FgYellow-33]
	_ = x[FgBlue-34]
	_ = x[FgMagenta-35]
	_ = x[FgCyan-36]
	_ = x[FgWhite-37]
	_ = x[FgDefault-39]
}

const (
	_FgColor_name_0 = "FgBlackFgRedFgGreenFgYellowFgBlueFgMagentaFgCyanFgWhite"
	_FgColor_name_1 = "FgDefault"
)

var (
	_FgColor_index_0 = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}
)

func (i FgColor) String() string {
	switch {
	case 30 <= i && i <= 37:
		i -= 30
		return _FgColor_name_0[_FgColor_index_0[i]:_FgColor_index_0[i+1]]
	case i == 39:
		return _FgColor_name_1
	default:
		return "FgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBrightBlack-90]
	_ = x[FgBrightRed-91]
	_ = x[FgBrightGreen-92]
	_ = x[FgBrightYellow-93]
	_ = x[FgBrightBlue-94]
	_ = x[FgBrightMagenta-95]
	_ = x[FgBrightCyan-96]
	_ = x[FgBrightWhite-97]
}

const _FgBrightColor_name = "FgBrightBlackFgBrightRedFgBrightGreenFgBrightYellowFgBrightBlueFgBrightMagentaFgBrightCyanFgBrightWhite"

var _FgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i FgBrightColor) String() string {
	idx := int(i) - 90
	if i < 90 || idx >= len(_FgBrightColor_index)-1 {
		return "FgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FgBrightColor_name[_FgBrightColor_index[idx]:_FgBrightColor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBlack-40]
	_ = x[BgRed-41]
	_ = x[BgGreen-42]
	_ = x[BgYellow-43]
	_ = x[BgBlue-44]
	_ = x[BgMagenta-45]
	_ = x[BgCyan-46]
	_ = x[BgWhite-47]
	_ = x[BgDefault-49]
}

const (
	_BgColor_name_0 = "BgBlackBgRedBgGreenBgYellowBgBlueBgMagentaBgCyanBgWhite"
	_BgColor_name_1 = "BgDefault"
)

var (
	_BgColor_index_0 = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}
)

func (i BgColor) String() string {
	switch {
	case 40 <= i && i <= 47:
		i -= 40
		return _BgColor_name_0[_BgColor_index_0[i]:_BgColor_index_0[i+1]]
	case i == 49:
		return _BgColor_name_1
	default:
		return "BgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBrightBlack-100]
	_ = x[BgBrightRed-101]
	_ = x[BgBrightGreen-102]
	_ = x[BgBrightYellow-103]
	_ = x[BgBrightBlue-104]
	_ = x[BgBrightMagenta-105]
	_ = x[BgBrightCyan-106]
	_ = x[BgBrightWhite-107]
}

const _BgBrightColor_name = "BgBrightBlackBgBrightRedBgBrightGreenBgBrightYellowBgBrightBlueBgBrightMagentaBgBrightCyanBgBrightWhite"

var _BgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i BgBrightColor) String() string {
	idx := int(i) - 100
	if i < 100 || idx >= len(_BgBrightColor_index)-1 {
		return "BgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BgBrightColor_name[_BgBrightColor_index[idx]:_BgBrightColor_index[idx+1]]
}
