// Code generated by "stringer -type=Key,SequenceType,Attr,FgColor,FgBrightColor,BgColor,BgBrightColor -output=vt_string.go"; DO NOT EDIT.

package vt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyUnknown-0]
	_ = x[KeyTab-1]
	_ = x[KeyShiftTab-2]
	_ = x[KeyUp-3]
	_ = x[KeyDown-4]
	_ = x[KeyRight-5]
	_ = x[KeyLeft-6]
	_ = x[KeyHome-7]
	_ = x[KeyEnd-8]
	_ = x[KeyCtrlUp-9]
	_ = x[KeyCtrlDown-10]
	_ = x[KeyCtrlRight-11]
	_ = x[KeyCtrlLeft-12]
	_ = x[KeyAltUp-13]
	_ = x[KeyAltDown-14]
	_ = x[KeyAltRight-15]
	_ = x[KeyAltLeft-16]
	_ = x[KeyShiftUp-17]
	_ = x[KeyShiftDown-18]
	_ = x[KeyShiftRight-19]
	_ = x[KeyShiftLeft-20]
	_ = x[KeyEnter-21]
	_ = x[KeyBackspace-22]
	_ = x[KeyPause-23]
	_ = x[KeyEsc-24]
	_ = x[KeyInsert-25]
	_ = x[KeyDelete-26]
	_ = x[KeyPageUp-27]
	_ = x[KeyPageDown-28]
	_ = x[KeyCtrlEnter-29]
	_ = x[KeyCtrlBackspace-30]
	_ = x[KeyF1-31]
	_ = x[KeyF2-32]
	_ = x[KeyF3-33]
	_ = x[KeyF4-34]
	_ = x[KeyF5-35]
	_ = x[KeyF6-36]
	_ = x[KeyF7-37]
	_ = x[KeyF8-38]
	_ = x[KeyF9-39]
	_ = x[KeyF10-40]
	_ = x[KeyF11-41]
	_ = x[KeyF12-42]
	_ = x[KeyCtrlA-43]
	_ = x[KeyCtrlB-44]
	_ = x[KeyCtrlC-45]
	_ = x[KeyCtrlD-46]
	_ = x[KeyCtrlE-47]
	_ = x[KeyCtrlF-48]
	_ = x[KeyCtrlG-49]
	_ = x[KeyCtrlH-50]
	_ = x[KeyCtrlI-51]
	_ = x[KeyCtrlJ-52]
	_ = x[KeyCtrlK-53]
	_ = x[KeyCtrlL-54]
	_ = x[KeyCtrlM-55]
	_ = x[KeyCtrlN-56]
	_ = x[KeyCtrlO-57]
	_ = x[KeyCtrlP-58]
	_ = x[KeyCtrlQ-59]
	_ = x[KeyCtrlR-60]
	_ = x[KeyCtrlS-61]
	_ = x[KeyCtrlT-62]
	_ = x[KeyCtrlU-63]
	_ = x[KeyCtrlV-64]
	_ = x[KeyCtrlW-65]
	_ = x[KeyCtrlX-66]
	_ = x[KeyCtrlY-67]
	_ = x[KeyCtrlZ-68]
	_ = x[KeyAltA-69]
	_ = x[KeyAltB-70]
	_ = x[KeyAltC-71]
	_ = x[KeyAltD-72]
	_ = x[KeyAltE-73]
	_ = x[KeyAltF-74]
	_ = x[KeyAltG-75]
	_ = x[KeyAltH-76]
	_ = x[KeyAltI-77]
	_ = x[KeyAltJ-78]
	_ = x[KeyAltK-79]
	_ = x[KeyAltL-80]
	_ = x[KeyAltM-81]
	_ = x[KeyAltN-82]
	_ = x[KeyAltO-83]
	_ = x[KeyAltP-84]
	_ = x[KeyAltQ-85]
	_ = x[KeyAltR-86]
	_ = x[KeyAltS-87]
	_ = x[KeyAltT-88]
	_ = x[KeyAltU-89]
	_ = x[KeyAltV-90]
	_ = x[KeyAltW-91]
	_ = x[KeyAltX-92]
	_ = x[KeyAltY-93]
	_ = x[KeyAltZ-94]
	_ = x[KeyAlt0-95]
	_ = x[KeyAlt1-96]
	_ = x[KeyAlt2-97]
	_ = x[KeyAlt3-98]
	_ = x[KeyAlt4-99]
	_ = x[KeyAlt5-100]
	_ = x[KeyAlt6-101]
	_ = x[KeyAlt7-102]
	_ = x[KeyAlt8-103]
	_ = x[KeyAlt9-104]
}

const _Key_name = "KeyUnknownKeyTabKeyShiftTabKeyUpKeyDownKeyRightKeyLeftKeyHomeKeyEndKeyCtrlUpKeyCtrlDownKeyCtrlRightKeyCtrlLeftKeyAltUpKeyAltDownKeyAltRightKeyAltLeftKeyShiftUpKeyShiftDownKeyShiftRightKeyShiftLeftKeyEnterKeyBackspaceKeyPauseKeyEscKeyInsertKeyDeleteKeyPageUpKeyPageDownKeyCtrlEnterKeyCtrlBackspaceKeyF1KeyF2KeyF3KeyF4KeyF5KeyF6KeyF7KeyF8KeyF9KeyF10KeyF11KeyF12KeyCtrlAKeyCtrlBKeyCtrlCKeyCtrlDKeyCtrlEKeyCtrlFKeyCtrlGKeyCtrlHKeyCtrlIKeyCtrlJKeyCtrlKKeyCtrlLKeyCtrlMKeyCtrlNKeyCtrlOKeyCtrlPKeyCtrlQKeyCtrlRKeyCtrlSKeyCtrlTKeyCtrlUKeyCtrlVKeyCtrlWKeyCtrlXKeyCtrlYKeyCtrlZKeyAltAKeyAltBKeyAltCKeyAltDKeyAltEKeyAltFKeyAltGKeyAltHKeyAltIKeyAltJKeyAltKKeyAltLKeyAltMKeyAltNKeyAltOKeyAltPKeyAltQKeyAltRKeyAltSKeyAltTKeyAltUKeyAltVKeyAltWKeyAltXKeyAltYKeyAltZKeyAlt0KeyAlt1KeyAlt2KeyAlt3KeyAlt4KeyAlt5KeyAlt6KeyAlt7KeyAlt8KeyAlt9"

var _Key_index = [...]uint16{0, 10, 16, 27, 32, 39, 47, 54, 61, 67, 76, 87, 99, 110, 118, 128, 139, 149, 159, 171, 184, 196, 204, 216, 224, 230, 239, 248, 257, 268, 280, 296, 301, 306, 311, 316, 321, 326, 331, 336, 341, 347, 353, 359, 367, 375, 383, 391, 399, 407, 415, 423, 431, 439, 447, 455, 463, 471, 479, 487, 495, 503, 511, 519, 527, 535, 543, 551, 559, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819}

func (i Key) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Key_index)-1 {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[idx]:_Key_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeqUnknown-0]
	_ = x[SeqEscape-1]
	_ = x[SeqUTF8-2]
	_ = x[SeqCSI-3]
	_ = x[SeqOSC-4]
	_ = x[SeqDCS-5]
	_ = x[SeqSS3-6]
	_ = x[SeqMeta-7]
	_ = x[SeqPaste-8]
}

const _SequenceType_name = "SeqUnknownSeqEscapeSeqUTF8SeqCSISeqOSCSeqDCSSeqSS3SeqMetaSeqPaste"

var _SequenceType_index = [...]uint8{0, 10, 19, 26, 32, 38, 44, 50, 57, 65}

func (i SequenceType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SequenceType_index)-1 {
		return "SequenceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SequenceType_name[_SequenceType_index[idx]:_SequenceType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrReset-0]
	_ = x[AttrBold-1]
	_ = x[AttrFaint-2]
	_ = x[AttrItalic-3]
	_ = x[AttrUnderline-4]
	_ = x[AttrBlinkSlow-5]
	_ = x[AttrBlinkRapid-6]
	_ = x[AttrReverseVideo-7]
	_ = x[AttrConceal-8]
	_ = x[AttrStrikethrough-9]
}

const _Attr_name = "AttrResetAttrBoldAttrFaintAttrItalicAttrUnderlineAttrBlinkSlowAttrBlinkRapidAttrReverseVideoAttrConcealAttrStrikethrough"

var _Attr_index = [...]uint8{0, 9, 17, 26, 36, 49, 62, 76, 92, 103, 120}

func (i Attr) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Attr_index)-1 {
		return "Attr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Attr_name[_Attr_index[idx]:_Attr_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBlack-30]
	_ = x[FgRed-31]
	_ = x[FgGreen-32]
	_ = x[FgYellow-33]
	_ = x[FgBlue-34]
	_ = x[FgMagenta-35]
	_ = x[FgCyan-36]
	_ = x[FgWhite-37]
}

const _FgColor_name = "FgBlackFgRedFgGreenFgYellowFgBlueFgMagentaFgCyanFgWhite"

var _FgColor_index = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}

func (i FgColor) String() string {
	idx := int(i) - 30
	if i < 30 || idx >= len(_FgColor_index)-1 {
		return "FgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FgColor_name[_FgColor_index[idx]:_FgColor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FgBrightBlack-90]
	_ = x[FgBrightRed-91]
	_ = x[FgBrightGreen-92]
	_ = x[FgBrightYellow-93]
	_ = x[FgBrightBlue-94]
	_ = x[FgBrightMagenta-95]
	_ = x[FgBrightCyan-96]
	_ = x[FgBrightWhite-97]
}

const _FgBrightColor_name = "FgBrightBlackFgBrightRedFgBrightGreenFgBrightYellowFgBrightBlueFgBrightMagentaFgBrightCyanFgBrightWhite"

var _FgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i FgBrightColor) String() string {
	idx := int(i) - 90
	if i < 90 || idx >= len(_FgBrightColor_index)-1 {
		return "FgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FgBrightColor_name[_FgBrightColor_index[idx]:_FgBrightColor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBlack-40]
	_ = x[BgRed-41]
	_ = x[BgGreen-42]
	_ = x[BgYellow-43]
	_ = x[BgBlue-44]
	_ = x[BgMagenta-45]
	_ = x[BgCyan-46]
	_ = x[BgWhite-47]
}

const _BgColor_name = "BgBlackBgRedBgGreenBgYellowBgBlueBgMagentaBgCyanBgWhite"

var _BgColor_index = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}

func (i BgColor) String() string {
	idx := int(i) - 40
	if i < 40 || idx >= len(_BgColor_index)-1 {
		return "BgColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BgColor_name[_BgColor_index[idx]:_BgColor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BgBrightBlack-100]
	_ = x[BgBrightRed-101]
	_ = x[BgBrightGreen-102]
	_ = x[BgBrightYellow-103]
	_ = x[BgBrightBlue-104]
	_ = x[BgBrightMagenta-105]
	_ = x[BgBrightCyan-106]
	_ = x[BgBrightWhite-107]
}

const _BgBrightColor_name = "BgBrightBlackBgBrightRedBgBrightGreenBgBrightYellowBgBrightBlueBgBrightMagentaBgBrightCyanBgBrightWhite"

var _BgBrightColor_index = [...]uint8{0, 13, 24, 37, 51, 63, 78, 90, 103}

func (i BgBrightColor) String() string {
	idx := int(i) - 100
	if i < 100 || idx >= len(_BgBrightColor_index)-1 {
		return "BgBrightColor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BgBrightColor_name[_BgBrightColor_index[idx]:_BgBrightColor_index[idx+1]]
}
