// Code generated by bitstringer; DO NOT EDIT.

package windowsx

import (
	"strings"

	"fmt"
)

func (i ControlKeyState) String() string {
	var parts []string
	if i&CAPSLOCK_ON != 0 {
		parts = append(parts, "CAPSLOCK_ON")
	}
	if i&ENHANCED_KEY != 0 {
		parts = append(parts, "ENHANCED_KEY")
	}
	if i&LEFT_ALT_PRESSED != 0 {
		parts = append(parts, "LEFT_ALT_PRESSED")
	}
	if i&LEFT_CTRL_PRESSED != 0 {
		parts = append(parts, "LEFT_CTRL_PRESSED")
	}
	if i&NUMLOCK_ON != 0 {
		parts = append(parts, "NUMLOCK_ON")
	}
	if i&RIGHT_ALT_PRESSED != 0 {
		parts = append(parts, "RIGHT_ALT_PRESSED")
	}
	if i&RIGHT_CTRL_PRESSED != 0 {
		parts = append(parts, "RIGHT_CTRL_PRESSED")
	}
	if i&SCROLLLOCK_ON != 0 {
		parts = append(parts, "SCROLLLOCK_ON")
	}
	if i&SHIFT_PRESSED != 0 {
		parts = append(parts, "SHIFT_PRESSED")
	}
	if len(parts) == 0 {
		return fmt.Sprintf("ControlKeyState(%d)", i)
	}
	return strings.Join(parts, "|")
}
