// Code generated by bitstringer; DO NOT EDIT.

package windowsx

import (
	"strings"

	"fmt"
)

func (i MouseEventFlag) String() string {
	var parts []string
	if i&MOUSE_MOVED != 0 {
		parts = append(parts, "MOUSE_MOVED")
	}
	if i&DOUBLE_CLICK != 0 {
		parts = append(parts, "DOUBLE_CLICK")
	}
	if i&MOUSE_WHEELED != 0 {
		parts = append(parts, "MOUSE_WHEELED")
	}
	if i&MOUSE_HWHEELED != 0 {
		parts = append(parts, "MOUSE_HWHEELED")
	}
	if len(parts) == 0 {
		return fmt.Sprintf("MouseEventFlag(%d)", i)
	}
	return strings.Join(parts, "|")
}
