// Code generated by bitstringer; DO NOT EDIT.

package windowsx

import (
	"strings"

	"fmt"
)

func (i MouseButtonState) String() string {
	var parts []string
	if i&FROM_LEFT_1ST_BUTTON_PRESSED != 0 {
		parts = append(parts, "FROM_LEFT_1ST_BUTTON_PRESSED")
	}
	if i&FROM_LEFT_2ND_BUTTON_PRESSED != 0 {
		parts = append(parts, "FROM_LEFT_2ND_BUTTON_PRESSED")
	}
	if i&FROM_LEFT_3RD_BUTTON_PRESSED != 0 {
		parts = append(parts, "FROM_LEFT_3RD_BUTTON_PRESSED")
	}
	if i&FROM_LEFT_4TH_BUTTON_PRESSED != 0 {
		parts = append(parts, "FROM_LEFT_4TH_BUTTON_PRESSED")
	}
	if i&RIGHTMOST_BUTTON_PRESSED != 0 {
		parts = append(parts, "RIGHTMOST_BUTTON_PRESSED")
	}
	if len(parts) == 0 {
		return fmt.Sprintf("MouseButtonState(%d)", i)
	}
	return strings.Join(parts, "|")
}
