//go:build windows

// Code generated by bitstringer -type=ControlKeyState,MouseButtonState,MouseEventFlag -output=types_bitstring.go; DO NOT EDIT.

package windowsx

import (
	"strconv"
	"strings"
)

var _ControlKeyState_values = []struct {
	val  ControlKeyState
	name string
}{
	{CAPSLOCK_ON, "CAPSLOCK_ON"},
	{ENHANCED_KEY, "ENHANCED_KEY"},
	{LEFT_ALT_PRESSED, "LEFT_ALT_PRESSED"},
	{LEFT_CTRL_PRESSED, "LEFT_CTRL_PRESSED"},
	{NUMLOCK_ON, "NUMLOCK_ON"},
	{RIGHT_ALT_PRESSED, "RIGHT_ALT_PRESSED"},
	{RIGHT_CTRL_PRESSED, "RIGHT_CTRL_PRESSED"},
	{SCROLLLOCK_ON, "SCROLLLOCK_ON"},
	{SHIFT_PRESSED, "SHIFT_PRESSED"},
}

func (i ControlKeyState) String() string {
	if i == 0 {
		return "0"
	}
	var parts []string
	for _, v := range _ControlKeyState_values {
		if i&v.val != 0 {
			parts = append(parts, v.name)
		}
	}
	if len(parts) == 0 {
		return strconv.FormatUint(uint64(i), 10)
	}
	return strings.Join(parts, "|")
}

var _MouseButtonState_values = []struct {
	val  MouseButtonState
	name string
}{
	{FROM_LEFT_1ST_BUTTON_PRESSED, "FROM_LEFT_1ST_BUTTON_PRESSED"},
	{FROM_LEFT_2ND_BUTTON_PRESSED, "FROM_LEFT_2ND_BUTTON_PRESSED"},
	{FROM_LEFT_3RD_BUTTON_PRESSED, "FROM_LEFT_3RD_BUTTON_PRESSED"},
	{FROM_LEFT_4TH_BUTTON_PRESSED, "FROM_LEFT_4TH_BUTTON_PRESSED"},
	{RIGHTMOST_BUTTON_PRESSED, "RIGHTMOST_BUTTON_PRESSED"},
}

func (i MouseButtonState) String() string {
	if i == 0 {
		return "0"
	}
	var parts []string
	for _, v := range _MouseButtonState_values {
		if i&v.val != 0 {
			parts = append(parts, v.name)
		}
	}
	if len(parts) == 0 {
		return strconv.FormatUint(uint64(i), 10)
	}
	return strings.Join(parts, "|")
}

var _MouseEventFlag_values = []struct {
	val  MouseEventFlag
	name string
}{
	{MOUSE_MOVED, "MOUSE_MOVED"},
	{DOUBLE_CLICK, "DOUBLE_CLICK"},
	{MOUSE_WHEELED, "MOUSE_WHEELED"},
	{MOUSE_HWHEELED, "MOUSE_HWHEELED"},
}

func (i MouseEventFlag) String() string {
	if i == 0 {
		return "0"
	}
	var parts []string
	for _, v := range _MouseEventFlag_values {
		if i&v.val != 0 {
			parts = append(parts, v.name)
		}
	}
	if len(parts) == 0 {
		return strconv.FormatUint(uint64(i), 10)
	}
	return strings.Join(parts, "|")
}
