package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

func main() {
	typeName := flag.String("type", "", "type name to generate String() for")
	flag.Parse()

	if *typeName == "" {
		log.Fatal("usage: bitstringer -type T")
	}

	fileName := os.Getenv("GOFILE")
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, fileName, nil, 0)
	if err != nil {
		log.Fatal(err)
	}

	var constants []string
	ast.Inspect(node, func(n ast.Node) bool {
		decl, ok := n.(*ast.ValueSpec)
		if !ok || decl.Type == nil {
			return true
		}

		// Match the type name (e.g., ControlKeyState)
		if ident, ok := decl.Type.(*ast.Ident); ok && ident.Name == *typeName {
			for _, name := range decl.Names {
				constants = append(constants, name.Name)
			}
		}
		return true
	})

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by bitstringer; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", node.Name.Name)
	fmt.Fprintf(&buf, "import (\n\n")
	fmt.Fprintf(&buf, "\"strings\" \n\n")
	fmt.Fprintf(&buf, "\"fmt\" ) \n\n")

	fmt.Fprintf(&buf, "func (i %s) String() string {\n", *typeName)
	fmt.Fprintf(&buf, "\tvar parts []string\n")

	for _, c := range constants {
		fmt.Fprintf(&buf, "\tif i&%s != 0 { parts = append(parts, %q) }\n", c, c)
	}

	text := "%d"
	fmt.Fprintf(&buf, "\tif len(parts) == 0 { return fmt.Sprintf(\"%s(%s)\", i) }\n", *typeName, text)
	fmt.Fprintf(&buf, "\treturn strings.Join(parts, \"|\")\n")
	fmt.Fprintf(&buf, "}\n")

	outName := fmt.Sprintf("%s_bitstring.go", strings.ToLower(*typeName))
	formatted, _ := format.Source(buf.Bytes())
	os.WriteFile(outName, formatted, 0644)
}
