package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

func main() {
	typeNamesList := flag.String("type", "", "comma-separated list of type names; must be set")
	outputFile := flag.String("output", "", "output file name; default src_bitstring.go")
	flag.Parse()

	if *typeNamesList == "" {
		fmt.Fprintf(os.Stderr, "error: -type must be provided\n")
		os.Exit(1)
	}

	typeNames := strings.Split(*typeNamesList, ",")
	for i := range typeNames {
		typeNames[i] = strings.TrimSpace(typeNames[i])
	}

	fileName := os.Getenv("GOFILE")
	if fileName == "" {
		fmt.Fprintf(os.Stderr, "error: bitstringer must be run via go generate\n")
		os.Exit(1)
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, fileName, nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("failed to parse: %v", err)
	}

	typeMap := make(map[string][]string)
	for _, name := range typeNames {
		typeMap[name] = []string{}
	}

	ast.Inspect(node, func(n ast.Node) bool {
		decl, ok := n.(*ast.ValueSpec)
		if !ok || decl.Type == nil {
			return true
		}
		if ident, ok := decl.Type.(*ast.Ident); ok {
			if _, exists := typeMap[ident.Name]; exists {
				for _, name := range decl.Names {
					typeMap[ident.Name] = append(typeMap[ident.Name], name.Name)
				}
			}
		}
		return true
	})

	var buf bytes.Buffer
	invocation := fmt.Sprintf("bitstringer %s", strings.Join(os.Args[1:], " "))
	fmt.Fprintf(&buf, "// Code generated by %s; DO NOT EDIT.\n\n", invocation)
	fmt.Fprintf(&buf, "package %s\n\n", node.Name.Name)
	fmt.Fprintf(&buf, "import (\n\t\"strconv\"\n\t\"strings\"\n)\n\n")

	for _, name := range typeNames {
		constants := typeMap[name]
		if len(constants) == 0 {
			continue
		}

		valVar := "_" + name + "_values"
		fmt.Fprintf(&buf, "var %s = []struct {\n\tval %s\n\tname string\n}{\n", valVar, name)
		for _, c := range constants {
			fmt.Fprintf(&buf, "\t{%s, %q},\n", c, c)
		}
		fmt.Fprintf(&buf, "}\n\n")

		fmt.Fprintf(&buf, "func (i %s) String() string {\n", name)
		fmt.Fprintf(&buf, "\tif i == 0 { return \"0\" }\n")
		fmt.Fprintf(&buf, "\tvar parts []string\n")
		fmt.Fprintf(&buf, "\tfor _, v := range %s {\n", valVar)
		fmt.Fprintf(&buf, "\t\tif i&v.val != 0 {\n\t\t\tparts = append(parts, v.name)\n\t\t}\n\t}\n")
		fmt.Fprintf(&buf, "\tif len(parts) == 0 {\n")
		fmt.Fprintf(&buf, "\t\treturn strconv.FormatUint(uint64(i), 10)\n")
		fmt.Fprintf(&buf, "\t}\n")
		fmt.Fprintf(&buf, "\treturn strings.Join(parts, \"|\")\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	out := *outputFile
	if out == "" {
		out = strings.TrimSuffix(fileName, ".go") + "_bitstring.go"
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format error: %v", err)
	}

	if err := os.WriteFile(out, formatted, 0644); err != nil {
		log.Fatalf("writing output: %v", err)
	}
}
